# -*- coding: utf-8 -*-
"""
Created on Thu Apr 20 17:38:01 2023

@author: aoosh
"""

RECTANGLULAR = 700

WINDOW_WIDTH = RECTANGLULAR
WINDOW_HEIGHT = RECTANGLULAR

AWAY_FROM_BOUNDARY = 100

UPPER_VELOCITY = 20
LOWER_VELOCITY = 5